# -*- coding: utf-8 -*-
"""
Created on Tue Dec  5 10:45:45 2017

@author: Christian
"""

# -*- coding: utf-8 -*-
"""
odeint
Quick results analysis of a folder of sgf files generated by Leela Zero.
"""

import os
import glob
import re
import numpy as np
import matplotlib.pyplot as plt

path = 'C:\\Users\\Christian\\Downloads\\all.sgf\\'
results = []
playerlist = []

for filename in glob.glob(os.path.join(path, '*.sgf')):
    print(filename)
    f = open(filename)
    for line in f:
           res = re.search(r'RE\[(.*?)\]',line)
           if res:
               title = res.group(1)
               results.append(title)
               
               playersearch = re.search(r'Leela Zero .*? (.*?)\]',line)
               if playersearch:
                   playername = playersearch.group(1)
               else:
                   playername = 'Unknown'
               playerlist.append(playername)            
    f.close()
#%%
resultsNum = [w.replace('B+', '').replace('W+', '-').replace('Resign','400') for w in results]
resultsNumpyStrings = np.asarray(resultsNum)
resultsNumpy = np.asfarray(resultsNumpyStrings,float)
#%%
playersNumpy = np.asarray(playerlist)

for network in ['6f274ab1','22373747','92c658d7','a1151640']:
    networkgameindices = np.where(playersNumpy == network)[0]
    networkresults = resultsNumpy[networkgameindices]

    myfig = plt.figure(figsize=(9,6))
    #plt.hist(networkresults,bins= np.arange(-400.5,400.5,1))
    plt.hist(networkresults,bins= np.arange(-90.5,90.5,1))
    plt.title('Scores of %d games from \'all.sgf.xz\' dated 05-Dec-2017 10:34\nNetwork: %s, positive = black win' % (networkresults.size,network) )
    #plt.title('Scores of %d games from \'all.sgf.xz\' dated 05-Dec-2017 10:34\nNetwork: %s, positive = black win, resign mapped to +/- 400' % (networkresults.size,network) )
    #plt.yscale('log', nonposy='clip')
    plt.show()
    myfig.savefig(network+'.png')
#%%
