# -*- coding: utf-8 -*-
"""
odeint

Quick results analysis of a folder of sgf files generated by Leela Zero.
"""

import os
import glob
import re
import numpy as np
import matplotlib.pyplot as plt

path = 'C:\\Users\\patro\\Downloads\\leela-zero-0.6-windows\\latest\\'
results = []

for filename in glob.glob(os.path.join(path, '*.sgf')):
    print(filename)
    f = open(filename)
    for line in f:
           res = re.search(r'RE\[(.*?)\]',line)
           if res:
               title = res.group(1)
               print(title)
               results.append(title)
    f.close()

resultsNum = [w.replace('B+', '').replace('W+', '-') for w in results]
resultsNumpyStrings = np.asarray(resultsNum)
resultsNumpy = np.asfarray(resultsNumpyStrings,float)

plt.figure(figsize=(9,6))
plt.hist(resultsNumpy,bins= np.arange(-25.5,150.5,1))
plt.title('Scores of %d games of 6f274ab, positive = black win' % resultsNumpy.size)
plt.show()
#%%
